### ISSUE TITLE
windows build break due to missing qt patch

### ISSUE THREAD

**Issue by shi-yan** [mumble-voip/mumble-releng#18]
tried to build on windows, got this while building Qt5:

./qt5.build: line 46: /cygdrive/c/mumble/mumble-releng/buildenv/1.3.x/win32-static/patches/qt5-qssldiffiehellmanparameters.patch: No such file or directory

the file indeed doesn't exist

**Comment by mkrautz** [comment]
Fixed in 6f39d6260c7c728e8a483b026231a02f28d60b8e.

Sorry for the inconvenience.

**Comment by shi-yan** [comment]
I have synced to the tot, this issue is gone, but I have a new issue, and seems to be related:

        cl -c -nologo -Zc:wchar_t -Zi -FS -Ox -GF -MD -Zc:strictStrings -D_HAS_EXCEPTIONS=0 -MP -GR -GL -W3 -w34100 -w34189 -w44996 -DUNICODE -DWIN32 -DBROWSER_QTEXTBROWSER -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_HELP_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -DQT_OPENGL_ES_2 -DQT_OPENGL_ES_2_ANGLE -DQT_OPENGL_ES_2_ANGLE_STATIC -DGL_APICALL= -DEGLAPI= -DNDEBUG -I. -IC:\MumbleBuild\win32-static-1.3.x-2015-09-19-41b7a9b\mariadbclient\mariadbclient\include -IC:\MumbleBuild\win32-static-1.3.x-2015-09-19-41b7a9b\zlib\include -IC:\MumbleBuild\win32-static-1.3.x-2015-09-19-41b7a9b\OpenSSL\include -I..\..\shared\fontpanel -I..\..\..\include -I..\..\..\include\QtHelp -IC:\MumbleBuild\win32-static-1.3.x-2015-09-19-41b7a9b.build\qt-everywhere-opensource-src-5.5.0\qtbase\include -IC:\MumbleBuild\win32-static-1.3.x-2015-09-19-41b7a9b.build\qt-everywhere-opensource-src-5.5.0\qtbase\include\QtPrintSupport -IC:\MumbleBuild\win32-static-1.3.x-2015-09-19-41b7a9b.build\qt-everywhere-opensource-src-5.5.0\qtbase\include\QtWidgets -IC:\MumbleBuild\win32-static-1.3.x-2015-09-19-41b7a9b.build\qt-everywhere-opensource-src-5.5.0\qtbase\include\QtGui -IC:\MumbleBuild\win32-static-1.3.x-2015-09-19-41b7a9b.build\qt-everywhere-opensource-src-5.5.0\qtbase\include\QtANGLE -IC:\MumbleBuild\win32-static-1.3.x-2015-09-19-41b7a9b.build\qt-everywhere-opensource-src-5.5.0\qtbase\include\QtNetwork -IC:\MumbleBuild\win32-static-1.3.x-2015-09-19-41b7a9b.build\qt-everywhere-opensource-src-5.5.0\qtbase\include\QtSql -IC:\MumbleBuild\win32-static-1.3.x-2015-09-19-41b7a9b.build\qt-everywhere-opensource-src-5.5.0\qtbase\include\QtCore -I.moc\release -I.uic -IC:\MumbleBuild\win32-static-1.3.x-2015-09-19-41b7a9b.build\qt-everywhere-opensource-src-5.5.0\qtbase\mkspecs\win32-msvc2013  -Fo.obj\release\ @C:\cygwin64\tmp\nmBEF1.tmp
helpbrowsersupport.cpp
        link /DEBUG /OPT:REF /OPT:ICF /NOLOGO /DYNAMICBASE /NXCOMPAT /INCREMENTAL:NO /LTCG /SUBSYSTEM:WINDOWS,5.01 "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:..\..\..\bin\assistant.exe @C:\cygwin64\tmp\nmC599.tmp
   Creating library ..\..\..\bin\assistant.lib and object ..\..\..\bin\assistant.exp
Qt5Network.lib(qsslconfiguration.obj) : error LNK2001: unresolved external symbol "bool __cdecl operator==(class QSslDiffieHellmanParameters const &,class QSslDiffieHellmanParameters const &)" (??8@YA_NABVQSslDiffieHellmanParameters@@0@Z)
Qt5Network.lib(qsslconfiguration.obj) : error LNK2001: unresolved external symbol "public: static class QSslDiffieHellmanParameters __cdecl QSslDiffieHellmanParameters::defaultParameters(void)" (?defaultParameters@QSslDiffieHellmanParameters@@SA?AV1@XZ)
Qt5Network.lib(qsslconfiguration.obj) : error LNK2001: unresolved external symbol "public: __thiscall QSslDiffieHellmanParameters::~QSslDiffieHellmanParameters(void)" (??1QSslDiffieHellmanParameters@@QAE@XZ)
Qt5Network.lib(qsslconfiguration.obj) : error LNK2001: unresolved external symbol "public: __thiscall QSslDiffieHellmanParameters::QSslDiffieHellmanParameters(class QSslDiffieHellmanParameters const &)" (??0QSslDiffieHellmanParameters@@QAE@ABV0@@Z)
Qt5Network.lib(qsslconfiguration.obj) : error LNK2001: unresolved external symbol "public: class QSslDiffieHellmanParameters & __thiscall QSslDiffieHellmanParameters::operator=(class QSslDiffieHellmanParameters const &)" (??4QSslDiffieHellmanParameters@@QAEAAV0@ABV0@@Z)
Qt5Network.lib(qsslcontext_openssl.obj) : error LNK2001: unresolved external symbol "public: bool __thiscall QSslDiffieHellmanParameters::isValid(void)const " (?isValid@QSslDiffieHellmanParameters@@QBE_NXZ)
Qt5Network.lib(qsslcontext_openssl.obj) : error LNK2001: unresolved external symbol "public: bool __thiscall QSslDiffieHellmanParameters::isEmpty(void)const " (?isEmpty@QSslDiffieHellmanParameters@@QBE_NXZ)
..\..\..\bin\assistant.exe : fatal error LNK1120: 7 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\link.EXE"' : return code '0x460'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.

**Comment by shi-yan** [comment]
I checked the patch, the unresolved stuff seems to be there.

I guess this is due to yesterday's build failure. I need to perform a clean build. I will try again.

**Comment by shi-yan** [comment]
the problem was indeed due to dirty build. 

after cleaning my makefiles, things worked.

btw, why do we use Qt5.4.1 on mac, but Qt5.5 on win?
what's the difference between osx-universal and osx builds?

**Comment by mkrautz** [comment]
Excellent.

We use Qt 5.4.1 on OS X because I haven't gotten around to update it yet.

The difference between osx and osx-universal is that osx is modern x86_64 OS X (used to work on 10.6 and greater, but requirements might be higher now), and osx-universal is x86+ppc for OS X 10.4 and above.

**Comment by shi-yan** [comment]
Thank you for replying.

I have noticed two issues on mac when building mumble. I will work on windows first, so the mac issues are not pressing matters for me.

the first problem is a infinite symlink when installing openssl. it happens to openssl's manual folder. could be an openssl bug. the issue is quite similar to the problem mentioned here, not sure if they are the same problem:

http://webcache.googleusercontent.com/search?q=cache:4iTWTz_vBu8J:rt.openssl.org/Ticket/Display.html%3Fid%3D702%26user%3Dguest%26pass%3Dguest+&cd=4&hl=en&ct=clnk&gl=us

the second issue is building Qt5.4.1, There are many unresolved functions. I'm using mac os 10.11, the SDK has changed in xcode 7. I saw similar issues with other Qt projects, usually I need to add     QMAKE_MAC_SDK = macosx10.11

I wonder if updating to Qt5.5 could solve the problem.

I can investigate more.
